import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import CustomToastContainer from "@/components/Ui/ToastContainer";

const Shabnam = localFont({
  src: [
    {
      path: "../assets/fonts/Shabnam-FD.ttf",
      weight: "400",
      style: "normal",
    },
    // اگر بولد هم داری، اضافه کن:
    // {
    //   path: "../assets/fonts/Shabnam-Bold-FD.ttf",
    //   weight: "700",
    //   style: "normal",
    // },
  ],
  variable: "--font-shabnam",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Reafusion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className="" suppressHydrationWarning>
      <body className={`${Shabnam.variable} font-shabnam antialiased`}>
        {children}
        <CustomToastContainer />
      </body>
    </html>
  );
}